import type { QuestionSet } from "./types.ts";

export const questionSets: QuestionSet[] = [
  {
    id: "hiragana-a-ka",
    title: "あいうえお・かきくけこ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "あ", kanas: ["あ"] },
      { text: "い", kanas: ["い"] },
      { text: "う", kanas: ["う"] },
      { text: "え", kanas: ["え"] },
      { text: "お", kanas: ["お"] },
      { text: "か", kanas: ["か"] },
      { text: "き", kanas: ["き"] },
      { text: "く", kanas: ["く"] },
      { text: "け", kanas: ["け"] },
      { text: "こ", kanas: ["こ"] },
    ],
  },
  {
    id: "hiragana-sa-ta",
    title: "さしすせそ・たちつてと",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "さ", kanas: ["さ"] },
      { text: "し", kanas: ["し"] },
      { text: "す", kanas: ["す"] },
      { text: "せ", kanas: ["せ"] },
      { text: "そ", kanas: ["そ"] },
      { text: "た", kanas: ["た"] },
      { text: "ち", kanas: ["ち"] },
      { text: "つ", kanas: ["つ"] },
      { text: "て", kanas: ["て"] },
      { text: "と", kanas: ["と"] },
    ],
  },
  {
    id: "hiragana-na-ha",
    title: "なにぬねの・はひふへほ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "な", kanas: ["な"] },
      { text: "に", kanas: ["に"] },
      { text: "ぬ", kanas: ["ぬ"] },
      { text: "ね", kanas: ["ね"] },
      { text: "の", kanas: ["の"] },
      { text: "は", kanas: ["は"] },
      { text: "ひ", kanas: ["ひ"] },
      { text: "ふ", kanas: ["ふ"] },
      { text: "へ", kanas: ["へ"] },
      { text: "ほ", kanas: ["ほ"] },
    ],
  },
  {
    id: "hiragana-ma-ya",
    title: "まみむめも・やゆよ",
    category: "hiragana",
    questionCount: 8,
    randomOrder: false,
    questions: [
      { text: "ま", kanas: ["ま"] },
      { text: "み", kanas: ["み"] },
      { text: "む", kanas: ["む"] },
      { text: "め", kanas: ["め"] },
      { text: "も", kanas: ["も"] },
      { text: "や", kanas: ["や"] },
      { text: "ゆ", kanas: ["ゆ"] },
      { text: "よ", kanas: ["よ"] },
    ],
  },
  {
    id: "hiragana-ra-wa",
    title: "らりるれろ・わをん",
    category: "hiragana",
    questionCount: 8,
    randomOrder: false,
    questions: [
      { text: "ら", kanas: ["ら"] },
      { text: "り", kanas: ["り"] },
      { text: "る", kanas: ["る"] },
      { text: "れ", kanas: ["れ"] },
      { text: "ろ", kanas: ["ろ"] },
      { text: "わ", kanas: ["わ"] },
      { text: "を", kanas: ["を"] },
      { text: "ん", kanas: ["ん"] },
    ],
  },
  {
    id: "hiragana-ga-za",
    title: "がぎぐげご・ざじずぜぞ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "が", kanas: ["が"] },
      { text: "ぎ", kanas: ["ぎ"] },
      { text: "ぐ", kanas: ["ぐ"] },
      { text: "げ", kanas: ["げ"] },
      { text: "ご", kanas: ["ご"] },
      { text: "ざ", kanas: ["ざ"] },
      { text: "じ", kanas: ["じ"] },
      { text: "ず", kanas: ["ず"] },
      { text: "ぜ", kanas: ["ぜ"] },
      { text: "ぞ", kanas: ["ぞ"] },
    ],
  },
  {
    id: "hiragana-da-ba",
    title: "だぢづでど・ばびぶべぼ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "だ", kanas: ["だ"] },
      { text: "ぢ", kanas: ["ぢ"] },
      { text: "づ", kanas: ["づ"] },
      { text: "で", kanas: ["で"] },
      { text: "ど", kanas: ["ど"] },
      { text: "ば", kanas: ["ば"] },
      { text: "び", kanas: ["び"] },
      { text: "ぶ", kanas: ["ぶ"] },
      { text: "べ", kanas: ["べ"] },
      { text: "ぼ", kanas: ["ぼ"] },
    ],
  },
  {
    id: "hiragana-pa",
    title: "ぱぴぷぺぽ",
    category: "hiragana",
    questionCount: 5,
    randomOrder: false,
    questions: [
      { text: "ぱ", kanas: ["ぱ"] },
      { text: "ぴ", kanas: ["ぴ"] },
      { text: "ぷ", kanas: ["ぷ"] },
      { text: "ぺ", kanas: ["ぺ"] },
      { text: "ぽ", kanas: ["ぽ"] },
    ],
  },
  {
    id: "hiragana-kya-sya-tya",
    title: "きゃきゅきょ・しゃしゅしょ・ちゃちゅちょ",
    category: "hiragana",
    questionCount: 9,
    randomOrder: false,
    questions: [
      { text: "きゃ", kanas: ["きゃ"] },
      { text: "きゅ", kanas: ["きゅ"] },
      { text: "きょ", kanas: ["きょ"] },
      { text: "しゃ", kanas: ["しゃ"] },
      { text: "しゅ", kanas: ["しゅ"] },
      { text: "しょ", kanas: ["しょ"] },
      { text: "ちゃ", kanas: ["ちゃ"] },
      { text: "ちゅ", kanas: ["ちゅ"] },
      { text: "ちょ", kanas: ["ちょ"] },
    ],
  },
  {
    id: "hiragana-nya-hya",
    title: "にゃにゅにょ・ひゃひゅひょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "にゃ", kanas: ["にゃ"] },
      { text: "にゅ", kanas: ["にゅ"] },
      { text: "にょ", kanas: ["にょ"] },
      { text: "ひゃ", kanas: ["ひゃ"] },
      { text: "ひゅ", kanas: ["ひゅ"] },
      { text: "ひょ", kanas: ["ひょ"] },
    ],
  },
  {
    id: "hiragana-mya-rya",
    title: "みゃみゅみょ・りゃりゅりょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "みゃ", kanas: ["みゃ"] },
      { text: "みゅ", kanas: ["みゅ"] },
      { text: "みょ", kanas: ["みょ"] },
      { text: "りゃ", kanas: ["りゃ"] },
      { text: "りゅ", kanas: ["りゅ"] },
      { text: "りょ", kanas: ["りょ"] },
    ],
  },
  {
    id: "hiragana-gya-zya",
    title: "ぎゃぎゅぎょ・じゃじゅじょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "ぎゃ", kanas: ["ぎゃ"] },
      { text: "ぎゅ", kanas: ["ぎゅ"] },
      { text: "ぎょ", kanas: ["ぎょ"] },
      { text: "じゃ", kanas: ["じゃ"] },
      { text: "じゅ", kanas: ["じゅ"] },
      { text: "じょ", kanas: ["じょ"] },
    ],
  },
  {
    id: "hiragana-bya-pya",
    title: "びゃびゅびょ・ぴゃぴゅぴょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "びゃ", kanas: ["びゃ"] },
      { text: "びゅ", kanas: ["びゅ"] },
      { text: "びょ", kanas: ["びょ"] },
      { text: "ぴゃ", kanas: ["ぴゃ"] },
      { text: "ぴゅ", kanas: ["ぴゅ"] },
      { text: "ぴょ", kanas: ["ぴょ"] },
    ],
  },
  {
    id: "grade1-kanji",
    title: "１年生のかん字",
    category: "kanji",
    questionCount: 10,
    randomOrder: true,
    // 小学1年で習う教育漢字80字。読みは代表読み（訓読み優先、動詞・形容詞は送りがな込みの辞書形、
    // 交ぜ書きが自然な字は交ぜ書き）を1つ選ぶのを原則とし、日常でどちらも自然に使われる音訓・複数読みは
    // kanas に両方入れる（先頭が代表読み）。
    questions: [
      { text: "一", kanas: ["いち"] },
      { text: "右", kanas: ["みぎ"] },
      { text: "雨", kanas: ["あめ"] },
      { text: "円", kanas: ["えん"] },
      { text: "王", kanas: ["おう"] },
      { text: "音", kanas: ["おと"] },
      { text: "下", kanas: ["した"] },
      { text: "火", kanas: ["ひ"] },
      { text: "花", kanas: ["はな"] },
      { text: "貝", kanas: ["かい"] },
      { text: "学ぶ", kanas: ["まなぶ"] },
      { text: "気", kanas: ["き"] },
      { text: "九", kanas: ["きゅう"] },
      { text: "休む", kanas: ["やすむ"] },
      { text: "玉", kanas: ["たま", "ぎょく"] },
      { text: "金", kanas: ["きん", "かね"] },
      { text: "空", kanas: ["そら"] },
      { text: "月", kanas: ["つき"] },
      { text: "犬", kanas: ["いぬ"] },
      { text: "見る", kanas: ["みる"] },
      { text: "五", kanas: ["ご"] },
      { text: "口", kanas: ["くち"] },
      { text: "校", kanas: ["こう"] },
      { text: "左", kanas: ["ひだり"] },
      { text: "三", kanas: ["さん"] },
      { text: "山", kanas: ["やま"] },
      { text: "子", kanas: ["こ"] },
      { text: "四", kanas: ["し", "よん"] },
      { text: "糸", kanas: ["いと"] },
      { text: "字", kanas: ["じ"] },
      { text: "耳", kanas: ["みみ"] },
      { text: "七", kanas: ["しち", "なな"] },
      { text: "車", kanas: ["くるま"] },
      { text: "手", kanas: ["て"] },
      { text: "十", kanas: ["じゅう"] },
      { text: "出る", kanas: ["でる"] },
      { text: "女", kanas: ["おんな"] },
      { text: "小さい", kanas: ["ちいさい"] },
      { text: "上", kanas: ["うえ"] },
      { text: "森", kanas: ["もり"] },
      { text: "人", kanas: ["ひと"] },
      { text: "水", kanas: ["みず"] },
      { text: "正しい", kanas: ["ただしい"] },
      { text: "生きる", kanas: ["いきる"] },
      { text: "青", kanas: ["あお"] },
      { text: "夕", kanas: ["ゆう"] },
      { text: "石", kanas: ["いし"] },
      { text: "赤", kanas: ["あか"] },
      { text: "千", kanas: ["せん"] },
      { text: "川", kanas: ["かわ"] },
      { text: "先", kanas: ["さき"] },
      { text: "早い", kanas: ["はやい"] },
      { text: "草", kanas: ["くさ"] },
      { text: "足", kanas: ["あし"] },
      { text: "村", kanas: ["むら"] },
      { text: "大きい", kanas: ["おおきい"] },
      { text: "男", kanas: ["おとこ"] },
      { text: "竹", kanas: ["たけ"] },
      { text: "中", kanas: ["なか"] },
      { text: "虫", kanas: ["むし"] },
      { text: "町", kanas: ["まち"] },
      { text: "天", kanas: ["てん"] },
      { text: "田", kanas: ["た"] },
      { text: "土", kanas: ["つち"] },
      { text: "二", kanas: ["に"] },
      { text: "日", kanas: ["ひ", "にち"] },
      { text: "入る", kanas: ["はいる"] },
      { text: "年", kanas: ["とし", "ねん"] },
      { text: "白", kanas: ["しろ"] },
      { text: "八", kanas: ["はち"] },
      { text: "百", kanas: ["ひゃく"] },
      { text: "文", kanas: ["ぶん", "ふみ"] },
      { text: "木", kanas: ["き"] },
      { text: "本", kanas: ["ほん"] },
      { text: "名まえ", kanas: ["なまえ"] },
      { text: "目", kanas: ["め"] },
      { text: "立つ", kanas: ["たつ"] },
      { text: "力", kanas: ["ちから"] },
      { text: "林", kanas: ["はやし"] },
      { text: "六", kanas: ["ろく"] },
    ],
  },
  {
    id: "grade2-kanji",
    title: "２年生のかん字",
    category: "kanji",
    questionCount: 10,
    randomOrder: true,
    // 小学2年で習う教育漢字160字。1年生と同じ方針（動詞・形容詞になれる字は送りがな込みの辞書形、
    // 単独で意味が確定する名詞は単漢字の訓読み、訓読みが日常語として弱い/存在しない字は単漢字の音読み、
    // 単漢字では意味が弱い字は交ぜ書き）で読みを1つ選ぶのを原則とし、音訓どちらも日常的に使う字は
    // kanas に両方入れる（先頭が代表読み）。
    questions: [
      { text: "引く", kanas: ["ひく"] },
      { text: "羽", kanas: ["はね"] },
      { text: "雲", kanas: ["くも"] },
      { text: "園", kanas: ["えん"] },
      { text: "遠い", kanas: ["とおい"] },
      { text: "何", kanas: ["なに"] },
      { text: "科", kanas: ["か"] },
      { text: "夏", kanas: ["なつ"] },
      { text: "家", kanas: ["いえ"] },
      { text: "歌", kanas: ["うた"] },
      { text: "画", kanas: ["が"] },
      { text: "回る", kanas: ["まわる"] },
      { text: "会う", kanas: ["あう"] },
      { text: "海", kanas: ["うみ"] },
      { text: "絵", kanas: ["え"] },
      { text: "外", kanas: ["そと"] },
      { text: "角", kanas: ["かど", "かく"] },
      { text: "楽しい", kanas: ["たのしい"] },
      { text: "活", kanas: ["かつ"] },
      { text: "間", kanas: ["あいだ"] },
      { text: "丸", kanas: ["まる"] },
      { text: "岩", kanas: ["いわ"] },
      { text: "顔", kanas: ["かお"] },
      { text: "汽", kanas: ["き"] },
      { text: "記", kanas: ["き"] },
      { text: "帰る", kanas: ["かえる"] },
      { text: "弓", kanas: ["ゆみ"] },
      { text: "牛", kanas: ["うし"] },
      { text: "魚", kanas: ["さかな", "うお"] },
      { text: "京", kanas: ["きょう"] },
      { text: "強い", kanas: ["つよい"] },
      { text: "教える", kanas: ["おしえる"] },
      { text: "近い", kanas: ["ちかい"] },
      { text: "兄", kanas: ["あに"] },
      { text: "形", kanas: ["かたち"] },
      { text: "計る", kanas: ["はかる"] },
      { text: "元", kanas: ["もと"] },
      { text: "言う", kanas: ["いう"] },
      { text: "原", kanas: ["はら"] },
      { text: "戸", kanas: ["と"] },
      { text: "古い", kanas: ["ふるい"] },
      { text: "午", kanas: ["ご"] },
      { text: "後", kanas: ["あと"] },
      { text: "語", kanas: ["ご"] },
      { text: "工", kanas: ["こう"] },
      { text: "公", kanas: ["こう"] },
      { text: "広い", kanas: ["ひろい"] },
      { text: "交", kanas: ["こう"] },
      { text: "光", kanas: ["ひかり"] },
      { text: "考える", kanas: ["かんがえる"] },
      { text: "行く", kanas: ["いく"] },
      { text: "高い", kanas: ["たかい"] },
      { text: "黄", kanas: ["き"] },
      { text: "合う", kanas: ["あう"] },
      { text: "谷", kanas: ["たに"] },
      { text: "国", kanas: ["くに"] },
      { text: "黒", kanas: ["くろ"] },
      { text: "今", kanas: ["いま"] },
      { text: "才", kanas: ["さい"] },
      { text: "細い", kanas: ["ほそい"] },
      { text: "作る", kanas: ["つくる"] },
      { text: "算", kanas: ["さん"] },
      { text: "止まる", kanas: ["とまる"] },
      { text: "市", kanas: ["いち", "し"] },
      { text: "矢", kanas: ["や"] },
      { text: "姉", kanas: ["あね"] },
      { text: "思う", kanas: ["おもう"] },
      { text: "紙", kanas: ["かみ"] },
      { text: "寺", kanas: ["てら"] },
      { text: "自", kanas: ["じ"] },
      { text: "時", kanas: ["とき"] },
      { text: "室", kanas: ["しつ"] },
      { text: "社", kanas: ["しゃ"] },
      { text: "弱い", kanas: ["よわい"] },
      { text: "首", kanas: ["くび"] },
      { text: "秋", kanas: ["あき"] },
      { text: "週", kanas: ["しゅう"] },
      { text: "春", kanas: ["はる"] },
      { text: "書く", kanas: ["かく"] },
      { text: "少ない", kanas: ["すくない"] },
      { text: "場", kanas: ["ば"] },
      { text: "色", kanas: ["いろ"] },
      { text: "食べる", kanas: ["たべる"] },
      { text: "心", kanas: ["こころ"] },
      { text: "新しい", kanas: ["あたらしい"] },
      { text: "親", kanas: ["おや"] },
      { text: "図", kanas: ["ず"] },
      { text: "数", kanas: ["かず"] },
      { text: "西", kanas: ["にし"] },
      { text: "声", kanas: ["こえ"] },
      { text: "星", kanas: ["ほし"] },
      { text: "晴れる", kanas: ["はれる"] },
      { text: "切る", kanas: ["きる"] },
      { text: "雪", kanas: ["ゆき"] },
      { text: "船", kanas: ["ふね"] },
      { text: "線", kanas: ["せん"] },
      { text: "前", kanas: ["まえ"] },
      { text: "組", kanas: ["くみ"] },
      { text: "走る", kanas: ["はしる"] },
      { text: "多い", kanas: ["おおい"] },
      { text: "太い", kanas: ["ふとい"] },
      { text: "体", kanas: ["からだ"] },
      { text: "台", kanas: ["だい"] },
      { text: "地", kanas: ["ち"] },
      { text: "池", kanas: ["いけ"] },
      { text: "知る", kanas: ["しる"] },
      { text: "茶", kanas: ["ちゃ"] },
      { text: "昼", kanas: ["ひる"] },
      { text: "長い", kanas: ["ながい"] },
      { text: "鳥", kanas: ["とり"] },
      { text: "朝", kanas: ["あさ"] },
      { text: "直す", kanas: ["なおす"] },
      { text: "通る", kanas: ["とおる"] },
      { text: "弟", kanas: ["おとうと"] },
      { text: "店", kanas: ["みせ"] },
      { text: "点", kanas: ["てん"] },
      { text: "電", kanas: ["でん"] },
      { text: "刀", kanas: ["かたな"] },
      { text: "冬", kanas: ["ふゆ"] },
      { text: "当たる", kanas: ["あたる"] },
      { text: "東", kanas: ["ひがし"] },
      { text: "答える", kanas: ["こたえる"] },
      { text: "頭", kanas: ["あたま"] },
      { text: "同じ", kanas: ["おなじ"] },
      { text: "道", kanas: ["みち"] },
      { text: "読む", kanas: ["よむ"] },
      { text: "内", kanas: ["うち"] },
      { text: "南", kanas: ["みなみ"] },
      { text: "肉", kanas: ["にく"] },
      { text: "馬", kanas: ["うま"] },
      { text: "売る", kanas: ["うる"] },
      { text: "買う", kanas: ["かう"] },
      { text: "麦", kanas: ["むぎ"] },
      { text: "半", kanas: ["はん"] },
      { text: "番", kanas: ["ばん"] },
      { text: "父", kanas: ["ちち"] },
      { text: "風", kanas: ["かぜ"] },
      { text: "分かる", kanas: ["わかる"] },
      { text: "聞く", kanas: ["きく"] },
      { text: "米", kanas: ["こめ"] },
      { text: "歩く", kanas: ["あるく"] },
      { text: "母", kanas: ["はは"] },
      { text: "方", kanas: ["ほう", "かた"] },
      { text: "北", kanas: ["きた"] },
      { text: "毎", kanas: ["まい"] },
      { text: "妹", kanas: ["いもうと"] },
      { text: "万", kanas: ["まん"] },
      { text: "明るい", kanas: ["あかるい"] },
      { text: "鳴く", kanas: ["なく"] },
      { text: "毛", kanas: ["け"] },
      { text: "門", kanas: ["もん"] },
      { text: "夜", kanas: ["よる"] },
      { text: "野", kanas: ["の"] },
      { text: "友", kanas: ["とも"] },
      { text: "用", kanas: ["よう"] },
      { text: "曜", kanas: ["よう"] },
      { text: "来る", kanas: ["くる"] },
      { text: "里", kanas: ["さと"] },
      { text: "理", kanas: ["り"] },
      { text: "話", kanas: ["はなし"] },
    ],
  },
  {
    id: "land-animals",
    title: "どうぶつ",
    category: "animals",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "犬", kanas: ["いぬ"] },
      { text: "ねこ", kanas: ["ねこ"] },
      { text: "うさぎ", kanas: ["うさぎ"] },
      { text: "象", kanas: ["ぞう"] },
      { text: "きりん", kanas: ["きりん"] },
      { text: "パンダ", kanas: ["ぱんだ"] },
      { text: "ライオン", kanas: ["らいおん"] },
      { text: "とら", kanas: ["とら"] },
      { text: "熊", kanas: ["くま"] },
      { text: "羊", kanas: ["ひつじ"] },
      { text: "牛", kanas: ["うし"] },
      { text: "ぶた", kanas: ["ぶた"] },
    ],
  },
  {
    id: "sea-creatures",
    title: "うみのいきもの",
    category: "animals",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "いるか", kanas: ["いるか"] },
      { text: "かめ", kanas: ["かめ"] },
      { text: "くじら", kanas: ["くじら"] },
      { text: "さめ", kanas: ["さめ"] },
      { text: "たこ", kanas: ["たこ"] },
      { text: "いか", kanas: ["いか"] },
      { text: "かに", kanas: ["かに"] },
      { text: "えび", kanas: ["えび"] },
      { text: "ペンギン", kanas: ["ぺんぎん"] },
      { text: "あざらし", kanas: ["あざらし"] },
      { text: "ラッコ", kanas: ["らっこ"] },
      { text: "くらげ", kanas: ["くらげ"] },
    ],
  },
  {
    id: "sky-creatures",
    title: "そらのいきもの",
    category: "animals",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "ふくろう", kanas: ["ふくろう"] },
      { text: "にわとり", kanas: ["にわとり"] },
      { text: "すずめ", kanas: ["すずめ"] },
      { text: "つばめ", kanas: ["つばめ"] },
      { text: "はと", kanas: ["はと"] },
      { text: "わし", kanas: ["わし"] },
      { text: "とんぼ", kanas: ["とんぼ"] },
      { text: "ちょう", kanas: ["ちょう"] },
      { text: "せみ", kanas: ["せみ"] },
      { text: "かぶとむし", kanas: ["かぶとむし"] },
    ],
  },
  {
    id: "meals",
    title: "ごはん",
    category: "foods",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "おにぎり", kanas: ["おにぎり"] },
      { text: "すし", kanas: ["すし"] },
      { text: "ラーメン", kanas: ["らーめん"] },
      { text: "カレー", kanas: ["かれー"] },
      { text: "焼肉", kanas: ["やきにく"] },
      { text: "たこ焼き", kanas: ["たこやき"] },
      // 「餃子」は現代中国語からの借用で厳密には外来語（→カタカナ）だが、
      // 日本語での慣用表記が「ぎょうざ」なので慣用を優先する。
      { text: "ぎょうざ", kanas: ["ぎょうざ"] },
      { text: "サンドイッチ", kanas: ["さんどいっち"] },
      { text: "ハンバーグ", kanas: ["はんばーぐ"] },
      { text: "オムライス", kanas: ["おむらいす"] },
      { text: "うどん", kanas: ["うどん"] },
      { text: "パン", kanas: ["ぱん"] },
    ],
  },
  {
    id: "fruits",
    title: "くだもの",
    category: "foods",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "りんご", kanas: ["りんご"] },
      { text: "バナナ", kanas: ["ばなな"] },
      { text: "ぶどう", kanas: ["ぶどう"] },
      { text: "いちご", kanas: ["いちご"] },
      { text: "みかん", kanas: ["みかん"] },
      { text: "もも", kanas: ["もも"] },
      { text: "梨", kanas: ["なし"] },
      { text: "メロン", kanas: ["めろん"] },
      { text: "すいか", kanas: ["すいか"] },
      { text: "キウイ", kanas: ["きうい"] },
    ],
  },
  {
    id: "sweets",
    title: "スイーツ",
    category: "foods",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "ケーキ", kanas: ["けーき"] },
      { text: "アイス", kanas: ["あいす"] },
      { text: "プリン", kanas: ["ぷりん"] },
      { text: "チョコ", kanas: ["ちょこ"] },
      { text: "クッキー", kanas: ["くっきー"] },
      { text: "ドーナツ", kanas: ["どーなつ"] },
      { text: "ゼリー", kanas: ["ぜりー"] },
      { text: "せんべい", kanas: ["せんべい"] },
      { text: "ガム", kanas: ["がむ"] },
      { text: "わたあめ", kanas: ["わたあめ"] },
      { text: "おかし", kanas: ["おかし"] },
    ],
  },
  {
    id: "land-vehicles",
    title: "りくののりもの",
    category: "vehicles",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "電車", kanas: ["でんしゃ"] },
      { text: "新幹線", kanas: ["しんかんせん"] },
      { text: "バス", kanas: ["ばす"] },
      { text: "タクシー", kanas: ["たくしー"] },
      { text: "車", kanas: ["くるま"] },
      { text: "自転車", kanas: ["じてんしゃ"] },
      { text: "オートバイ", kanas: ["おーとばい"] },
      { text: "トラック", kanas: ["とらっく"] },
      { text: "消防車", kanas: ["しょうぼうしゃ"] },
      { text: "救急車", kanas: ["きゅうきゅうしゃ"] },
      { text: "パトカー", kanas: ["ぱとかー"] },
      { text: "地下鉄", kanas: ["ちかてつ"] },
    ],
  },
  {
    id: "sky-vehicles",
    title: "そらののりもの",
    category: "vehicles",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "飛行機", kanas: ["ひこうき"] },
      { text: "ヘリコプター", kanas: ["へりこぷたー"] },
      { text: "ロケット", kanas: ["ろけっと"] },
      { text: "気球", kanas: ["ききゅう"] },
      { text: "グライダー", kanas: ["ぐらいだー"] },
      { text: "飛行船", kanas: ["ひこうせん"] },
      { text: "スペースシャトル", kanas: ["すぺーすしゃとる"] },
      { text: "ドローン", kanas: ["どろーん"] },
      { text: "パラグライダー", kanas: ["ぱらぐらいだー"] },
      { text: "紙飛行機", kanas: ["かみひこうき"] },
    ],
  },
  {
    id: "sea-vehicles",
    title: "うみののりもの",
    category: "vehicles",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "船", kanas: ["ふね"] },
      { text: "ヨット", kanas: ["よっと"] },
      { text: "せんすいかん", kanas: ["せんすいかん"] },
      { text: "カヌー", kanas: ["かぬー"] },
      { text: "いかだ", kanas: ["いかだ"] },
      { text: "タンカー", kanas: ["たんかー"] },
      { text: "モーターボート", kanas: ["もーたーぼーと"] },
      { text: "フェリー", kanas: ["ふぇりー"] },
      { text: "ゴムボート", kanas: ["ごむぼーと"] },
      { text: "漁船", kanas: ["ぎょせん"] },
    ],
  },
  {
    id: "ball-sports",
    title: "きゅうぎ",
    category: "sports",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "野球", kanas: ["やきゅう"] },
      { text: "サッカー", kanas: ["さっかー"] },
      { text: "テニス", kanas: ["てにす"] },
      { text: "バスケットボール", kanas: ["ばすけっとぼーる"] },
      { text: "バレーボール", kanas: ["ばれーぼーる"] },
      { text: "たっきゅう", kanas: ["たっきゅう"] },
      { text: "ゴルフ", kanas: ["ごるふ"] },
      { text: "バドミントン", kanas: ["ばどみんとん"] },
      { text: "ドッジボール", kanas: ["どっじぼーる"] },
      { text: "ラグビー", kanas: ["らぐびー"] },
      { text: "ハンドボール", kanas: ["はんどぼーる"] },
    ],
  },
  {
    id: "martial-arts",
    title: "かくとうぎ",
    category: "sports",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "じゅうどう", kanas: ["じゅうどう"] },
      { text: "空手", kanas: ["からて"] },
      { text: "すもう", kanas: ["すもう"] },
      { text: "ボクシング", kanas: ["ぼくしんぐ"] },
      { text: "けんどう", kanas: ["けんどう"] },
      { text: "レスリング", kanas: ["れすりんぐ"] },
      { text: "合気道", kanas: ["あいきどう"] },
      { text: "弓道", kanas: ["きゅうどう"] },
      { text: "テコンドー", kanas: ["てこんどー"] },
      { text: "カンフー", kanas: ["かんふー"] },
    ],
  },
  {
    id: "subjects",
    title: "きょうか",
    category: "school",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "国語", kanas: ["こくご"] },
      { text: "算数", kanas: ["さんすう"] },
      { text: "理科", kanas: ["りか"] },
      { text: "社会", kanas: ["しゃかい"] },
      { text: "体育", kanas: ["たいいく"] },
      { text: "音楽", kanas: ["おんがく"] },
      { text: "図工", kanas: ["ずこう"] },
      { text: "家庭科", kanas: ["かていか"] },
      { text: "英語", kanas: ["えいご"] },
      { text: "道徳", kanas: ["どうとく"] },
    ],
  },
  {
    id: "school-items",
    title: "がっこうのどうぐ",
    category: "school",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "消しゴム", kanas: ["けしごむ"] },
      { text: "えんぴつ", kanas: ["えんぴつ"] },
      { text: "ランドセル", kanas: ["らんどせる"] },
      { text: "教科書", kanas: ["きょうかしょ"] },
      { text: "ノート", kanas: ["のーと"] },
      { text: "定規", kanas: ["じょうぎ"] },
      { text: "はさみ", kanas: ["はさみ"] },
      { text: "のり", kanas: ["のり"] },
      { text: "筆箱", kanas: ["ふでばこ"] },
      { text: "クレヨン", kanas: ["くれよん"] },
      { text: "計算機", kanas: ["けいさんき"] },
      { text: "コンパス", kanas: ["こんぱす"] },
    ],
  },
];

// URL から渡ってきた setId をセットに解決する共通ヘルパ。
// 見つからない場合は undefined を返し、呼び出し側（ルータの beforeLoad）が / へリダイレクトする。
export function findQuestionSet(id: string): QuestionSet | undefined {
  return questionSets.find((set) => set.id === id);
}
