import type { QuestionSet } from "./types.ts";

export const questionSets: QuestionSet[] = [
  {
    id: "hiragana-a-ka",
    title: "あいうえお・かきくけこ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "あ", kana: "あ" },
      { text: "い", kana: "い" },
      { text: "う", kana: "う" },
      { text: "え", kana: "え" },
      { text: "お", kana: "お" },
      { text: "か", kana: "か" },
      { text: "き", kana: "き" },
      { text: "く", kana: "く" },
      { text: "け", kana: "け" },
      { text: "こ", kana: "こ" },
    ],
  },
  {
    id: "hiragana-sa-ta",
    title: "さしすせそ・たちつてと",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "さ", kana: "さ" },
      { text: "し", kana: "し" },
      { text: "す", kana: "す" },
      { text: "せ", kana: "せ" },
      { text: "そ", kana: "そ" },
      { text: "た", kana: "た" },
      { text: "ち", kana: "ち" },
      { text: "つ", kana: "つ" },
      { text: "て", kana: "て" },
      { text: "と", kana: "と" },
    ],
  },
  {
    id: "hiragana-na-ha",
    title: "なにぬねの・はひふへほ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "な", kana: "な" },
      { text: "に", kana: "に" },
      { text: "ぬ", kana: "ぬ" },
      { text: "ね", kana: "ね" },
      { text: "の", kana: "の" },
      { text: "は", kana: "は" },
      { text: "ひ", kana: "ひ" },
      { text: "ふ", kana: "ふ" },
      { text: "へ", kana: "へ" },
      { text: "ほ", kana: "ほ" },
    ],
  },
  {
    id: "hiragana-ma-ya",
    title: "まみむめも・やゆよ",
    category: "hiragana",
    questionCount: 8,
    randomOrder: false,
    questions: [
      { text: "ま", kana: "ま" },
      { text: "み", kana: "み" },
      { text: "む", kana: "む" },
      { text: "め", kana: "め" },
      { text: "も", kana: "も" },
      { text: "や", kana: "や" },
      { text: "ゆ", kana: "ゆ" },
      { text: "よ", kana: "よ" },
    ],
  },
  {
    id: "hiragana-ra-wa",
    title: "らりるれろ・わをん",
    category: "hiragana",
    questionCount: 8,
    randomOrder: false,
    questions: [
      { text: "ら", kana: "ら" },
      { text: "り", kana: "り" },
      { text: "る", kana: "る" },
      { text: "れ", kana: "れ" },
      { text: "ろ", kana: "ろ" },
      { text: "わ", kana: "わ" },
      { text: "を", kana: "を" },
      { text: "ん", kana: "ん" },
    ],
  },
  {
    id: "hiragana-ga-za",
    title: "がぎぐげご・ざじずぜぞ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "が", kana: "が" },
      { text: "ぎ", kana: "ぎ" },
      { text: "ぐ", kana: "ぐ" },
      { text: "げ", kana: "げ" },
      { text: "ご", kana: "ご" },
      { text: "ざ", kana: "ざ" },
      { text: "じ", kana: "じ" },
      { text: "ず", kana: "ず" },
      { text: "ぜ", kana: "ぜ" },
      { text: "ぞ", kana: "ぞ" },
    ],
  },
  {
    id: "hiragana-da-ba",
    title: "だぢづでど・ばびぶべぼ",
    category: "hiragana",
    questionCount: 10,
    randomOrder: false,
    questions: [
      { text: "だ", kana: "だ" },
      { text: "ぢ", kana: "ぢ" },
      { text: "づ", kana: "づ" },
      { text: "で", kana: "で" },
      { text: "ど", kana: "ど" },
      { text: "ば", kana: "ば" },
      { text: "び", kana: "び" },
      { text: "ぶ", kana: "ぶ" },
      { text: "べ", kana: "べ" },
      { text: "ぼ", kana: "ぼ" },
    ],
  },
  {
    id: "hiragana-pa",
    title: "ぱぴぷぺぽ",
    category: "hiragana",
    questionCount: 5,
    randomOrder: false,
    questions: [
      { text: "ぱ", kana: "ぱ" },
      { text: "ぴ", kana: "ぴ" },
      { text: "ぷ", kana: "ぷ" },
      { text: "ぺ", kana: "ぺ" },
      { text: "ぽ", kana: "ぽ" },
    ],
  },
  {
    id: "hiragana-kya-sya-tya",
    title: "きゃきゅきょ・しゃしゅしょ・ちゃちゅちょ",
    category: "hiragana",
    questionCount: 9,
    randomOrder: false,
    questions: [
      { text: "きゃ", kana: "きゃ" },
      { text: "きゅ", kana: "きゅ" },
      { text: "きょ", kana: "きょ" },
      { text: "しゃ", kana: "しゃ" },
      { text: "しゅ", kana: "しゅ" },
      { text: "しょ", kana: "しょ" },
      { text: "ちゃ", kana: "ちゃ" },
      { text: "ちゅ", kana: "ちゅ" },
      { text: "ちょ", kana: "ちょ" },
    ],
  },
  {
    id: "hiragana-nya-hya",
    title: "にゃにゅにょ・ひゃひゅひょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "にゃ", kana: "にゃ" },
      { text: "にゅ", kana: "にゅ" },
      { text: "にょ", kana: "にょ" },
      { text: "ひゃ", kana: "ひゃ" },
      { text: "ひゅ", kana: "ひゅ" },
      { text: "ひょ", kana: "ひょ" },
    ],
  },
  {
    id: "hiragana-mya-rya",
    title: "みゃみゅみょ・りゃりゅりょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "みゃ", kana: "みゃ" },
      { text: "みゅ", kana: "みゅ" },
      { text: "みょ", kana: "みょ" },
      { text: "りゃ", kana: "りゃ" },
      { text: "りゅ", kana: "りゅ" },
      { text: "りょ", kana: "りょ" },
    ],
  },
  {
    id: "hiragana-gya-zya",
    title: "ぎゃぎゅぎょ・じゃじゅじょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "ぎゃ", kana: "ぎゃ" },
      { text: "ぎゅ", kana: "ぎゅ" },
      { text: "ぎょ", kana: "ぎょ" },
      { text: "じゃ", kana: "じゃ" },
      { text: "じゅ", kana: "じゅ" },
      { text: "じょ", kana: "じょ" },
    ],
  },
  {
    id: "hiragana-bya-pya",
    title: "びゃびゅびょ・ぴゃぴゅぴょ",
    category: "hiragana",
    questionCount: 6,
    randomOrder: false,
    questions: [
      { text: "びゃ", kana: "びゃ" },
      { text: "びゅ", kana: "びゅ" },
      { text: "びょ", kana: "びょ" },
      { text: "ぴゃ", kana: "ぴゃ" },
      { text: "ぴゅ", kana: "ぴゅ" },
      { text: "ぴょ", kana: "ぴょ" },
    ],
  },
  {
    id: "land-animals",
    title: "どうぶつ",
    category: "animals",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "犬", kana: "いぬ" },
      { text: "ねこ", kana: "ねこ" },
      { text: "うさぎ", kana: "うさぎ" },
      { text: "象", kana: "ぞう" },
      { text: "きりん", kana: "きりん" },
      { text: "パンダ", kana: "ぱんだ" },
      { text: "ライオン", kana: "らいおん" },
      { text: "とら", kana: "とら" },
      { text: "熊", kana: "くま" },
      { text: "羊", kana: "ひつじ" },
      { text: "牛", kana: "うし" },
      { text: "ぶた", kana: "ぶた" },
    ],
  },
  {
    id: "sea-creatures",
    title: "うみのいきもの",
    category: "animals",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "いるか", kana: "いるか" },
      { text: "かめ", kana: "かめ" },
      { text: "くじら", kana: "くじら" },
      { text: "さめ", kana: "さめ" },
      { text: "たこ", kana: "たこ" },
      { text: "いか", kana: "いか" },
      { text: "かに", kana: "かに" },
      { text: "えび", kana: "えび" },
      { text: "ペンギン", kana: "ぺんぎん" },
      { text: "あざらし", kana: "あざらし" },
      { text: "ラッコ", kana: "らっこ" },
      { text: "くらげ", kana: "くらげ" },
    ],
  },
  {
    id: "sky-creatures",
    title: "そらのいきもの",
    category: "animals",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "ふくろう", kana: "ふくろう" },
      { text: "にわとり", kana: "にわとり" },
      { text: "すずめ", kana: "すずめ" },
      { text: "つばめ", kana: "つばめ" },
      { text: "はと", kana: "はと" },
      { text: "わし", kana: "わし" },
      { text: "とんぼ", kana: "とんぼ" },
      { text: "ちょう", kana: "ちょう" },
      { text: "せみ", kana: "せみ" },
      { text: "かぶとむし", kana: "かぶとむし" },
    ],
  },
  {
    id: "meals",
    title: "ごはん",
    category: "foods",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "おにぎり", kana: "おにぎり" },
      { text: "すし", kana: "すし" },
      { text: "ラーメン", kana: "らーめん" },
      { text: "カレー", kana: "かれー" },
      { text: "焼肉", kana: "やきにく" },
      { text: "たこ焼き", kana: "たこやき" },
      // 「餃子」は現代中国語からの借用で厳密には外来語（→カタカナ）だが、
      // 日本語での慣用表記が「ぎょうざ」なので慣用を優先する。
      { text: "ぎょうざ", kana: "ぎょうざ" },
      { text: "サンドイッチ", kana: "さんどいっち" },
      { text: "ハンバーグ", kana: "はんばーぐ" },
      { text: "オムライス", kana: "おむらいす" },
      { text: "うどん", kana: "うどん" },
      { text: "パン", kana: "ぱん" },
    ],
  },
  {
    id: "fruits",
    title: "くだもの",
    category: "foods",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "りんご", kana: "りんご" },
      { text: "バナナ", kana: "ばなな" },
      { text: "ぶどう", kana: "ぶどう" },
      { text: "いちご", kana: "いちご" },
      { text: "みかん", kana: "みかん" },
      { text: "もも", kana: "もも" },
      { text: "梨", kana: "なし" },
      { text: "メロン", kana: "めろん" },
      { text: "すいか", kana: "すいか" },
      { text: "キウイ", kana: "きうい" },
    ],
  },
  {
    id: "sweets",
    title: "スイーツ",
    category: "foods",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "ケーキ", kana: "けーき" },
      { text: "アイス", kana: "あいす" },
      { text: "プリン", kana: "ぷりん" },
      { text: "チョコ", kana: "ちょこ" },
      { text: "クッキー", kana: "くっきー" },
      { text: "ドーナツ", kana: "どーなつ" },
      { text: "ゼリー", kana: "ぜりー" },
      { text: "せんべい", kana: "せんべい" },
      { text: "ガム", kana: "がむ" },
      { text: "わたあめ", kana: "わたあめ" },
      { text: "おかし", kana: "おかし" },
    ],
  },
  {
    id: "land-vehicles",
    title: "りくののりもの",
    category: "vehicles",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "電車", kana: "でんしゃ" },
      { text: "新幹線", kana: "しんかんせん" },
      { text: "バス", kana: "ばす" },
      { text: "タクシー", kana: "たくしー" },
      { text: "車", kana: "くるま" },
      { text: "自転車", kana: "じてんしゃ" },
      { text: "オートバイ", kana: "おーとばい" },
      { text: "トラック", kana: "とらっく" },
      { text: "消防車", kana: "しょうぼうしゃ" },
      { text: "救急車", kana: "きゅうきゅうしゃ" },
      { text: "パトカー", kana: "ぱとかー" },
      { text: "地下鉄", kana: "ちかてつ" },
    ],
  },
  {
    id: "sky-vehicles",
    title: "そらののりもの",
    category: "vehicles",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "飛行機", kana: "ひこうき" },
      { text: "ヘリコプター", kana: "へりこぷたー" },
      { text: "ロケット", kana: "ろけっと" },
      { text: "気球", kana: "ききゅう" },
      { text: "グライダー", kana: "ぐらいだー" },
      { text: "飛行船", kana: "ひこうせん" },
      { text: "スペースシャトル", kana: "すぺーすしゃとる" },
      { text: "ドローン", kana: "どろーん" },
      { text: "パラグライダー", kana: "ぱらぐらいだー" },
      { text: "紙飛行機", kana: "かみひこうき" },
    ],
  },
  {
    id: "sea-vehicles",
    title: "うみののりもの",
    category: "vehicles",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "船", kana: "ふね" },
      { text: "ヨット", kana: "よっと" },
      { text: "せんすいかん", kana: "せんすいかん" },
      { text: "カヌー", kana: "かぬー" },
      { text: "いかだ", kana: "いかだ" },
      { text: "タンカー", kana: "たんかー" },
      { text: "モーターボート", kana: "もーたーぼーと" },
      { text: "フェリー", kana: "ふぇりー" },
      { text: "ゴムボート", kana: "ごむぼーと" },
      { text: "漁船", kana: "ぎょせん" },
    ],
  },
  {
    id: "ball-sports",
    title: "きゅうぎ",
    category: "sports",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "野球", kana: "やきゅう" },
      { text: "サッカー", kana: "さっかー" },
      { text: "テニス", kana: "てにす" },
      { text: "バスケットボール", kana: "ばすけっとぼーる" },
      { text: "バレーボール", kana: "ばれーぼーる" },
      { text: "たっきゅう", kana: "たっきゅう" },
      { text: "ゴルフ", kana: "ごるふ" },
      { text: "バドミントン", kana: "ばどみんとん" },
      { text: "ドッジボール", kana: "どっじぼーる" },
      { text: "ラグビー", kana: "らぐびー" },
      { text: "ハンドボール", kana: "はんどぼーる" },
    ],
  },
  {
    id: "martial-arts",
    title: "かくとうぎ",
    category: "sports",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "じゅうどう", kana: "じゅうどう" },
      { text: "空手", kana: "からて" },
      { text: "すもう", kana: "すもう" },
      { text: "ボクシング", kana: "ぼくしんぐ" },
      { text: "けんどう", kana: "けんどう" },
      { text: "レスリング", kana: "れすりんぐ" },
      { text: "合気道", kana: "あいきどう" },
      { text: "弓道", kana: "きゅうどう" },
      { text: "テコンドー", kana: "てこんどー" },
      { text: "カンフー", kana: "かんふー" },
    ],
  },
  {
    id: "subjects",
    title: "きょうか",
    category: "school",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "国語", kana: "こくご" },
      { text: "算数", kana: "さんすう" },
      { text: "理科", kana: "りか" },
      { text: "社会", kana: "しゃかい" },
      { text: "体育", kana: "たいいく" },
      { text: "音楽", kana: "おんがく" },
      { text: "図工", kana: "ずこう" },
      { text: "家庭科", kana: "かていか" },
      { text: "英語", kana: "えいご" },
      { text: "道徳", kana: "どうとく" },
    ],
  },
  {
    id: "school-items",
    title: "がっこうのどうぐ",
    category: "school",
    questionCount: 6,
    randomOrder: true,
    questions: [
      { text: "消しゴム", kana: "けしごむ" },
      { text: "えんぴつ", kana: "えんぴつ" },
      { text: "ランドセル", kana: "らんどせる" },
      { text: "教科書", kana: "きょうかしょ" },
      { text: "ノート", kana: "のーと" },
      { text: "定規", kana: "じょうぎ" },
      { text: "はさみ", kana: "はさみ" },
      { text: "のり", kana: "のり" },
      { text: "筆箱", kana: "ふでばこ" },
      { text: "クレヨン", kana: "くれよん" },
      { text: "計算機", kana: "けいさんき" },
      { text: "コンパス", kana: "こんぱす" },
    ],
  },
];

// URL から渡ってきた setId をセットに解決する共通ヘルパ。
// 見つからない場合は undefined を返し、呼び出し側（ルータの beforeLoad）が / へリダイレクトする。
export function findQuestionSet(id: string): QuestionSet | undefined {
  return questionSets.find((set) => set.id === id);
}
